Feature: Oscillating patterns
  Scenario: Blinker
    Given we have a game:
      """life
      .....
      ..0..
      ..0..
      ..0..
      .....
      """
    When we advance the game
    Then the game state is:
      """life
      .....
      .....
      .000.
      .....
      .....
      """

    Given we have a game:
      """life
      .....
      .....
      .000.
      .....
      .....
      """
    When we advance the game
    Then the game state is:
      """life
      .....
      ..0..
      ..0..
      ..0..
      .....
      """

  Scenario: Blinker
    Given we have a game:
      """life
      ......
      ...0..
      .0..0,.
      .0..0,.
      ..0...
      ......
      """
    When we advance the game
    Then the game state is:
      """life
      ......
      ......
      ..000,.
      .000,..
      ......
      ......
      """

    Given we have a game:
      """life
      ......
      ......
      ..000,.
      .000,..
      ......
      ......
      """
    When we advance the game
    Then the game state is:
      """life
      ......
      ...0..
      .0..0,.
      .0..0,.
      ..0...
      ......
      """

  Scenario: Beacon
    Given we have a game:
      """life
      ......
      .00,...
      .0....
      ....0.
      ...00,.
      ......
      """
    When we advance the game
    Then the game state is:
      """life
      ......
      .00...
      .00...
      ...00.
      ...00.
      ......
      """

    Given we have a game:
      """life
      ......
      .00,...
      .00,...
      ...00,.
      ...00,.
      ......
      """
    When we advance the game
    Then the game state is:
      """life
      ......
      .00,...
      .0....
      ....0.
      ...00.
      ......
      """